### ISSUE TITLE
Document setting port

### ISSUE THREAD

**Issue by joshq00** [Cfeusier/general-cluster#1]
I see that `app.port || 3000` is used for port #.

Most express apps do `.listen( port )`. The readme says "instead of using `.listen`" but offers no explanation where those arguments now belong

Same goes for "how do I know when it's running?"

If I'm a user and I would normally write,

``` es6
.listen( 1234, () => console.log( 'something' ) )
```

explain what that becomes if we use your library

**Comment by Cfeusier** [comment]
Good questions, will get back to you on this tonight after work.
